// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpqcdrrbbvmoaiwmlhsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwcWNkcnJiYnZtb2Fpd21saHNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NDU1OTEsImV4cCI6MjA3MjAyMTU5MX0.WL0idWSLqy66fWUMXqhhEadrpVoiuZXdpS5hCQfDdMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});